require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  AutoCorrect: false
  Exclude:
    - db/schema.rb
    - spec/**/*.rb

Style/Alias:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylealias

Style/AsciiComments:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styleasciicomments

Style/BeginBlock:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylebeginblock

Style/BlockDelimiters:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styleblockdelimiters

Style/CommentAnnotation:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylecommentannotation

Style/Documentation:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styledocumentation

Layout/DotPosition:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#layoutdotposition

Style/DoubleNegation:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styledoublenegation

Style/EndBlock:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styleendblock

Style/FormatString:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styleformatstring

Style/IfUnlessModifier:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styleifunlessmodifier

Style/Lambda:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylelambda

Style/ModuleFunction:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylemodulefunction

Style/MultilineBlockChain:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylemultilineblockchain

Style/NegatedIf:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylenegatedif

Style/NegatedWhile:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylenegatedwhile

Style/ParallelAssignment:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styleparallelassignment

Style/PercentLiteralDelimiters:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylepercentliteraldelimiters

Style/PerlBackrefs:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styleperlbackrefs

Style/Semicolon:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylesemicolon

Style/SignalException:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylesignalexception

Style/SingleLineBlockParams:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylesinglelineblockparams

Style/SingleLineMethods:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylesinglelinemethods

Layout/SpaceBeforeBlockBraces:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#layoutspacebeforeblockbraces

Layout/SpaceInsideParens:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#layoutspaceinsideparens

Style/SpecialGlobalVars:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylespecialglobalvars

Style/StringLiterals:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylestringliterals

Style/TrailingCommaInArguments:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styletrailingcommainarguments

Style/TrailingCommaInArrayLiteral:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styletrailingcommainliteral

Style/TrailingCommaInHashLiteral:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styletrailingcommainliteral

Style/WhileUntilModifier:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylewhileuntilmodifier

Style/WordArray:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylewordarray

Lint/AmbiguousRegexpLiteral:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#lintambiguousregexpliteral

Lint/AssignmentInCondition:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#lintassignmentincondition

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# End of Relaxed.Ruby.Style

#
# Drivy's additions
#

# Customize cops

Metrics/BlockLength:
  Max: 30
  ExcludedMethods:
    - state_machine
  Exclude:
    - lib/tasks/**/*.rake
    - spec/**/*.rb

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  Exclude:
    - app/serializers/**/*.rb

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - db/**/*

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/AndOr:
  EnforcedStyle: conditionals

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

# Disable cops

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/AccessorMethodName:
  Exclude:
    - app/controllers/**/*.rb

Performance/Casecmp:
  Enabled: false

# Rails

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/FindBy:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/*.rb
